Lab5 ipynb added
akmorrow13/mcb-88-connector pull request #1
Opened 2017-03-02 22:57 UTC by rishab231

Lab5 ipynb has been created

The images folder should be in the same folder as the notebook. There are no subfolders within the images folder i.e. images folder contains all the images.

2017-03-02 23:06 UTC, akmorrow13 commented
@rishab231 please remove duplicate image files. They are already avilable in the image folder.

2017-03-04 00:40 UTC, akmorrow13 commented on exercises/lab5/lab5.ipynb
> +    "<img src=\"../images/lab5/locus.png\" width=\"100\" />\n",
I still dont think this is going to work. Have you tested in datahub?

2017-03-04 00:40 UTC, rishab231 commented on exercises/lab5/lab5.ipynb
> +    "<img src=\"../images/lab5/locus.png\" width=\"100\" />\n",
Yes I have tested it and it works

2017-03-04 00:41 UTC, akmorrow13 requested changes

2017-03-04 00:41 UTC, akmorrow13 commented on exercises/lab5.md
> -# Lab 5: How the Immune System Detects Mutations
Can you not delete this file?

2017-03-04 00:42 UTC, akmorrow13 commented on exercises/lab5/lab5.ipynb
> +    "<img src=\"../images/lab5/locus.png\" width=\"100\" />\n",
how did you upload it to datahub?

2017-03-04 01:16 UTC, merged